Introduce a heuristic to print floating point numbers more coincely
marzer/tomlplusplus pull request #89
Opened 2021-02-22 10:33 UTC by vaartis

**What does this change do?**

Introduces a heuristic that, for floating pointer numbers that have <=3 positions after the floating point, prints them with just those, and otherwise it prints them with the usual `std::numeric_limits<T>::digits10 + 1` precision.

**Is it related to an exisiting bug report or feature request?**

Continuation of #88 

**Pre-merge checklist**

- [x] I've read [CONTRIBUTING.md]
- [x] I've rebased my changes against the current HEAD of `origin/master` (if necessary)
- [ ] I've added new test cases to verify my change - no need, probably
- [x] I've regenerated toml.hpp ([how-to])
- [x] I've updated any affected documentation
- [ ] I've rebuilt and run the tests with at least one of: - again, probably no need
    - [ ] Clang 6 or higher
    - [ ] GCC 7 or higher
    - [ ] MSVC 19.20 (Visual Studio 2019) or higher
- [x] I've added my name to the list of contributors in [README.md](https://github.com/marzer/tomlplusplus/blob/master/README.md)

[CONTRIBUTING.md]: https://github.com/marzer/tomlplusplus/blob/master/CONTRIBUTING.md
[how-to]: https://github.com/marzer/tomlplusplus/blob/master/CONTRIBUTING.md#regenerating-tomlhpp
[README.md]: https://github.com/marzer/tomlplusplus/blob/master/README.md

2021-02-22 10:35 UTC, vaartis commented
I guess I do need to fix the tests somehow. I can't buld them because meson says `unknown target 'tests/cpp17'``...

2021-02-22 10:42 UTC, marzer requested changes
Also need to regen `toml.hpp` ^_^

2021-02-22 10:42 UTC, marzer commented on include/toml++/toml_print_to_stream.h
> +						? std::to_chars(buf, buf + sizeof(buf), val, std::chars_format::hex, decimal_places)
You don't need to do this in the hexfloat case; full precision is assumed for hexfloats (that's sorta the whole point of them).

2021-02-22 10:58 UTC, vaartis commented
After looking at the tests, I'm not sure this is possible to do while still retaining the round-trip thing, because "0.3" is not written as "0.30000000000000004" anymore, basically. I guess this isn't going to work out after all and I'll have to maintain a fork with precision setting disabled after all. Feel free to close this, I dont' really understand how to fix this issue.

2021-02-22 11:45 UTC, closed without merging

2021-02-22 11:50 UTC, marzer commented
> I dont' really understand how to fix this issue.
> 
> Hence this change breaks all the tests, basically. Sorry for wasting your time.

That's alright. It's kinda a damned-either-way scenario, really. Thanks for giving it a crack.

2021-11-10 20:24 UTC, marzer commented
@vaartis if you would still like this feature I can probably implement it trivially as part of the [v3 branch](https://github.com/marzer/tomlplusplus/tree/v3), since I now use the new `format_flags` for lots of other opt-in formatting stuff. Something like `format_flags::relaxed_float_precision`. Sound good?

2021-11-11 07:44 UTC, vaartis commented
> @vaartis if you would still like this feature I can probably implement it trivially as part of the [v3 branch](https://github.com/marzer/tomlplusplus/tree/v3), since I now use the new `format_flags` for lots of other opt-in formatting stuff. Something like `format_flags::relaxed_float_precision`. Sound good?

Please do! Then I can finally remove that fork I've been using with a single line changed..

2022-01-08 14:35 UTC, marzer commented
@vaartis I've implemented this in the v3 branch.

```toml
val1 =   0.010284358729827818
val2 =   0.0102
val3 =  10.0102
val4 =  10.010284358729827818
val5 =  10.0
```

```cpp
using formatter = toml::toml_formatter;
std::cout << cfg << "\n\n";
std::cout << formatter{ cfg, formatter::default_flags | toml::format_flags::relaxed_float_precision };
```

```sh
val1 = 0.010284358729827818
val2 = 0.0102
val3 = 10.0102
val4 = 10.010284358729828
val5 = 10.0

val1 = 0.0102844
val2 = 0.0102
val3 = 10.0102
val4 = 10.0103
val5 = 10.0
```

2022-01-08 20:28 UTC, vaartis commented
Thank you for implementing this. I think it's probably enough for it to be per-stream, for my use-case it certainly should be. Sort of busy with other things lately, so can't say how soon I can actually test it (since this means i'll also have to port other things like source locations to v3), but judging from your description this seems to be what I need.

2022-05-11 21:41 UTC, vaartis commented
Tested this one too and it seems to work fine :+1:

2022-05-12 07:17 UTC, marzer commented
Awesome, good to hear